import type { AchievementDefinition, AchievementRarity } from "./types";

export const RARITY_COLORS: Record<AchievementRarity, string> = {
  Comum: "#A9A9B2",
  Rara: "#0A84FF",
  Épica: "#BF5AF2",
  Lendária: "#FF9F0A",
  "Urso Mítico": "#B7FF2A",
};

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: "primeira-patada",
    title: "Primeira Patada",
    description: "Registrou a primeira refeição.",
    lockedHint: "Registre sua primeira refeição.",
    icon: "paw",
    category: "Primeiros passos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "A primeira patada deixa marca.",
    condition: (c) => c.totalMeals >= 1,
  },
  {
    id: "urso-voltou",
    title: "O Urso Voltou",
    description: "Registrou refeições durante 3 dias consecutivos.",
    lockedHint: "Volte e registre refeições por 3 dias seguidos.",
    icon: "teddy-bear",
    category: "Primeiros passos",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Três dias alimentando a máquina.",
    condition: (c) => c.bestStreak >= 3,
  },
  {
    id: "despensa-inaugurada",
    title: "Despensa Inaugurada",
    description: "Cadastrou o primeiro alimento pessoal.",
    lockedHint: "Cadastre um alimento na sua despensa.",
    icon: "food-apple",
    category: "Primeiros passos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "A despensa do urso está oficialmente aberta.",
    condition: (c) => c.personalFoods >= 1,
  },
  {
    id: "chef-da-caverna",
    title: "Chef da Caverna",
    description: "Criou a primeira receita.",
    lockedHint: "Monte sua primeira receita.",
    icon: "chef-hat",
    category: "Primeiros passos",
    rarity: "Rara",
    xpReward: 100,
    unlockMessage: "A caverna ganhou um chef.",
    condition: (c) => c.recipes >= 1,
  },
  {
    id: "semana-honesta",
    title: "Uma Semaninha Honesta",
    description: "Manteve uma sequência de 7 dias.",
    lockedHint: "Alcance uma sequência de 7 dias.",
    icon: "fire",
    category: "Primeiros passos",
    rarity: "Rara",
    xpReward: 150,
    unlockMessage: "Consistência com cheiro de vitória.",
    condition: (c) => c.bestStreak >= 7,
  },
  {
    id: "pata-firme",
    title: "Firme igual pata de urso",
    description: "Manteve uma sequência de 14 dias.",
    lockedHint: "Alcance uma sequência de 14 dias.",
    icon: "paw-outline",
    category: "Primeiros passos",
    rarity: "Épica",
    xpReward: 250,
    unlockMessage: "Duas semanas. Essa pata está firme.",
    condition: (c) => c.bestStreak >= 14,
  },
  {
    id: "virou-rotina",
    title: "Isso aqui virou rotina",
    description: "Manteve uma sequência de 30 dias.",
    lockedHint: "Alcance uma sequência de 30 dias.",
    icon: "calendar-check",
    category: "Primeiros passos",
    rarity: "Épica",
    xpReward: 400,
    unlockMessage: "A rotina já sabe seu nome.",
    condition: (c) => c.bestStreak >= 30,
  },
  {
    id: "virou-personalidade",
    title: "Isso já virou personalidade",
    description: "Manteve uma sequência de 60 dias.",
    lockedHint: "Alcance uma sequência de 60 dias.",
    icon: "calendar-star",
    category: "Primeiros passos",
    rarity: "Lendária",
    xpReward: 800,
    unlockMessage: "A constância agora faz parte do personagem.",
    condition: (c) => c.bestStreak >= 60,
  },
  {
    id: "absoluto",
    title: "ABSOLUTO",
    description: "Manteve uma sequência de 100 dias.",
    lockedHint: "A floresta conta os dias de uma lenda.",
    icon: "crown",
    category: "Primeiros passos",
    rarity: "Urso Mítico",
    xpReward: 1500,
    unlockMessage: "Cem dias. Absolutamente enorme.",
    condition: (c) => c.bestStreak >= 100,
  },
  {
    id: "proteina-sobrenome",
    title: "Proteína é meu sobrenome",
    description: "Bateu a meta de proteína pela primeira vez.",
    lockedHint: "Alcance a meta diária de proteína.",
    icon: "arm-flex",
    category: "Proteína",
    rarity: "Rara",
    xpReward: 100,
    unlockMessage: "Hoje o urso alimentou os músculos.",
    condition: (c) => c.proteinGoalDays >= 1,
  },
  {
    id: "cade-whey",
    title: "Cadê o Whey?",
    description: "Registrou whey pela primeira vez.",
    lockedHint: "Há rumores de um shaker pela floresta.",
    icon: "shaker-outline",
    category: "Proteína",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Shaker localizado. Missão cumprida.",
    condition: (c) => c.wheyMeals >= 1,
  },
  {
    id: "wheyyyyy",
    title: "WHEYYYYY",
    description: "Registrou whey 50 vezes.",
    lockedHint: "O shaker ainda tem muitas histórias.",
    icon: "shaker",
    category: "Proteína",
    rarity: "Épica",
    xpReward: 500,
    unlockMessage: "A floresta inteira ouviu esse WHEYYYYY.",
    condition: (c) => c.wheyMeals >= 50,
  },
  {
    id: "inimigo-galinhas",
    title: "Inimigo Natural das Galinhas",
    description: "Registrou frango 100 vezes.",
    lockedHint: "Continue registrando suas fontes de proteína.",
    icon: "food-drumstick",
    category: "Proteína",
    rarity: "Épica",
    xpReward: 500,
    unlockMessage: "As galinhas já conhecem a lenda.",
    condition: (c) => c.chickenMeals >= 100,
  },
  {
    id: "urso-onivoro",
    title: "Urso Onívoro",
    description: "Consumiu alimentos de 5 categorias no mesmo dia.",
    lockedHint: "Explore mais cores e categorias no prato.",
    icon: "food-apple-outline",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 200,
    unlockMessage: "A variedade também alimenta o shape.",
    condition: (c) => c.variedFoodDays >= 1,
  },
  {
    id: "equilibrio-padawan",
    title: "Equilíbrio, jovem padawan",
    description: "Terminou o dia dentro de 5% da meta calórica.",
    lockedHint: "Chegue com leveza perto da meta do dia.",
    icon: "scale-balance",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 150,
    unlockMessage: "Equilíbrio desbloqueado. Sem neura.",
    condition: (c) => c.calorieBalanceDays >= 1,
  },
  {
    id: "refeicao-livre",
    title: "Nem só de frango vive o urso",
    description: "Registrou uma refeição livre.",
    lockedHint: "Uma refeição diferente também cabe na rotina.",
    icon: "pizza",
    category: "Alimentação",
    rarity: "Comum",
    xpReward: 100,
    unlockMessage: "Flexibilidade também faz parte do plano.",
    condition: (c) => c.freeMeals >= 1,
  },
  {
    id: "vida-real",
    title: "A Vida Acontece",
    description: "Registrou uma refeição fora do plano.",
    lockedHint: "Registre com honestidade uma refeição fora do plano.",
    icon: "silverware-variant",
    category: "Alimentação",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Sem culpa. O registro verdadeiro vale muito.",
    condition: (c) => c.offPlanMeals >= 1,
  },
  {
    id: "proxima-refeicao",
    title: "A Próxima Refeição Conta",
    description: "Voltou ao plano depois de uma refeição excepcional.",
    lockedHint: "Depois de sair do plano, retome na próxima oportunidade.",
    icon: "backup-restore",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 175,
    unlockMessage: "Consistência é voltar, não ser perfeito.",
    condition: (c) => c.returnedToPlanAfterOffPlan,
  },
  {
    id: "tudo-sob-controle",
    title: "Tudo sob controle",
    description: "Fez uma refeição mais calórica e terminou o dia perto da meta.",
    lockedHint: "Equilíbrio vale mais do que perfeição.",
    icon: "meditation",
    category: "Alimentação",
    rarity: "Épica",
    xpReward: 300,
    unlockMessage: "O urso sabe equilibrar as coisas.",
    condition: (c) => c.controlledHighCalorieDays >= 1,
  },
  {
    id: "plot-twist",
    title: "Plot Twist Nutricional",
    description: "Registrou uma refeição com mais de 1.000 kcal.",
    lockedHint: "Algumas refeições chegam com reviravolta.",
    icon: "hamburger",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 125,
    unlockMessage: "Plot twist registrado. Vida que segue.",
    condition: (c) => c.veryHighCalorieMeals >= 1,
  },
  {
    id: "acontece",
    title: "Acontece nas melhores famílias",
    description: "Ultrapassou a meta calórica e continuou registrando.",
    lockedHint: "Registrar com honestidade sempre conta.",
    icon: "emoticon-happy-outline",
    category: "Alimentação",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Sem culpa. Informação ajuda, julgamento não.",
    condition: (c) => c.overGoalDays >= 1,
  },
  {
    id: "voltou-normal",
    title: "Voltou como se nada tivesse acontecido",
    description: "Depois de ultrapassar a meta, registrou no dia seguinte.",
    lockedHint: "Retornar à rotina é uma grande conquista.",
    icon: "restart",
    category: "Alimentação",
    rarity: "Épica",
    xpReward: 350,
    unlockMessage: "Consistência não exige perfeição.",
    condition: (c) => c.returnedAfterOverGoal,
  },
  {
    id: "primeiro-gole",
    title: "Primeiro Gole",
    description: "Registrou água pela primeira vez.",
    lockedHint: "Registre seu primeiro gole de água.",
    icon: "cup-water",
    category: "Água",
    rarity: "Comum",
    xpReward: 35,
    unlockMessage: "A hidratação começou. Gole por gole.",
    condition: (c) => c.waterRecords >= 1,
  },
  {
    id: "recipiente-fiel",
    title: "Recipiente Fiel",
    description: "Usou um recipiente salvo pela primeira vez.",
    lockedHint: "Cadastre e use um recipiente favorito.",
    icon: "bottle-soda-classic-outline",
    category: "Água",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "Seu recipiente já faz parte da rotina.",
    condition: (c) => c.customContainerUses >= 1,
  },
  {
    id: "hidraturso",
    title: "HidratUrso",
    description: "Bateu a meta diária de água.",
    lockedHint: "Complete sua meta diária de água.",
    icon: "water",
    category: "Água",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Hidratação premium desbloqueada.",
    condition: (c) => c.waterGoalDays >= 1,
  },
  {
    id: "aquaman-academia",
    title: "Aquaman da Academia",
    description: "Bateu a meta de água por 7 dias consecutivos.",
    lockedHint: "Mantenha a meta de água por uma semana.",
    icon: "waves",
    category: "Água",
    rarity: "Rara",
    xpReward: 250,
    unlockMessage: "Sete dias navegando na hidratação.",
    condition: (c) => c.waterBestStreak >= 7,
  },
  {
    id: "agua-premium",
    title: "100% Água Premium",
    description: "Bateu a meta de água por 30 dias consecutivos.",
    lockedHint: "Transforme hidratação em rotina.",
    icon: "cup-water",
    category: "Água",
    rarity: "Lendária",
    xpReward: 750,
    unlockMessage: "A hidratação agora é lendária.",
    condition: (c) => c.waterBestStreak >= 30,
  },
  {
    id: "primeiro-treino",
    title: "Urso em Movimento",
    description: "Concluiu a primeira sessão de treino.",
    lockedHint: "Conclua sua primeira sessão.",
    icon: "arm-flex-outline",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "O primeiro treino entrou para o histórico.",
    condition: (c) => c.workoutSessions >= 1,
  },
  {
    id: "primeira-musculacao",
    title: "Ferro Encontrado",
    description: "Concluiu a primeira sessão de musculação.",
    lockedHint: "Conclua uma musculação.",
    icon: "dumbbell",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "Musculação registrada, sem inventar carga.",
    condition: (c) => c.strengthSessions >= 1,
  },
  {
    id: "primeira-mobilidade",
    title: "Urso Destravado",
    description: "Concluiu a primeira sessão de mobilidade.",
    lockedHint: "Conclua uma sessão de alongamento.",
    icon: "human-handsup",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "Mobilidade também é treino.",
    condition: (c) => c.mobilitySessions >= 1,
  },
  {
    id: "primeira-corrida",
    title: "Pegadas na Floresta",
    description: "Concluiu a primeira corrida.",
    lockedHint: "Conclua uma corrida.",
    icon: "run-fast",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "A primeira corrida ficou marcada.",
    condition: (c) => c.runningSessions >= 1,
  },
  {
    id: "primeira-bike",
    title: "Urso sobre Rodas",
    description: "Concluiu a primeira sessão de bike.",
    lockedHint: "Conclua uma sessão de bike.",
    icon: "bike-fast",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "Primeiro pedal registrado.",
    condition: (c) => c.cyclingSessions >= 1,
  },
  {
    id: "primeiro-wod",
    title: "WOD Desbloqueado",
    description: "Concluiu a primeira sessão de CrossFit.",
    lockedHint: "Conclua um WOD.",
    icon: "weight-lifter",
    category: "Treinos",
    rarity: "Rara",
    xpReward: 100,
    unlockMessage: "WOD concluído e preservado no histórico.",
    condition: (c) => c.crossfitSessions >= 1,
  },
  {
    id: "primeira-atividade-personalizada",
    title: "Do Seu Jeito",
    description: "Concluiu a primeira atividade personalizada.",
    lockedHint: "Conclua uma atividade criada por você.",
    icon: "star-outline",
    category: "Treinos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "Atividade personalizada registrada.",
    condition: (c) => c.customSessions >= 1,
  },
  {
    id: "primeiro-recorde",
    title: "Novo Recorde",
    description: "Registrou o primeiro recorde pessoal válido.",
    lockedHint: "Supere uma marca anterior.",
    icon: "medal-outline",
    category: "Treinos",
    rarity: "Rara",
    xpReward: 120,
    unlockMessage: "Recorde confirmado — sem duplicidade.",
    condition: (c) => c.personalRecords >= 1,
  },
  {
    id: "primeiros-5k",
    title: "Primeiros 5K",
    description: "Concluiu uma corrida de pelo menos 5 km.",
    lockedHint: "Registre uma corrida de 5 km.",
    icon: "map-marker-distance",
    category: "Treinos",
    rarity: "Rara",
    xpReward: 150,
    unlockMessage: "Cinco quilômetros na conta.",
    condition: (c) => c.fiveKmRuns >= 1,
  },
  {
    id: "primeiros-10k",
    title: "Primeiros 10K",
    description: "Concluiu uma corrida de pelo menos 10 km.",
    lockedHint: "Registre uma corrida de 10 km.",
    icon: "map-marker-path",
    category: "Treinos",
    rarity: "Épica",
    xpReward: 300,
    unlockMessage: "Dez quilômetros. O urso foi longe.",
    condition: (c) => c.tenKmRuns >= 1,
  },
  {
    id: "semana-completa-treino",
    title: "Semana em Movimento",
    description: "Treinou em pelo menos 3 dias da mesma semana.",
    lockedHint: "Conclua treinos em 3 dias da semana.",
    icon: "calendar-check-outline",
    category: "Treinos",
    rarity: "Rara",
    xpReward: 180,
    unlockMessage: "Semana completa do jeito que foi planejada.",
    condition: (c) => c.completeTrainingWeeks >= 1,
  },
  {
    id: "combo-modalidades",
    title: "Dia Multimodal",
    description: "Concluiu duas modalidades diferentes no mesmo dia.",
    lockedHint: "Registre duas modalidades no mesmo dia.",
    icon: "view-dashboard-variant-outline",
    category: "Treinos",
    rarity: "Rara",
    xpReward: 125,
    unlockMessage: "Cada sessão contou separadamente.",
    condition: (c) => c.multiModalityDays >= 1,
  },
  {
    id: "sequencia-treinos-7",
    title: "Sete Dias em Movimento",
    description: "Treinou por 7 dias consecutivos.",
    lockedHint: "Mantenha uma sequência de 7 dias.",
    icon: "fire",
    category: "Treinos",
    rarity: "Épica",
    xpReward: 350,
    unlockMessage: "Sete dias registrados sem punir os dias de descanso.",
    condition: (c) => c.workoutBestStreak >= 7,
  },
  {
    id: "muitos-ovos",
    title: "Ovos. Muitos ovos.",
    description: "Registrou 6 ou mais ovos no mesmo dia.",
    lockedHint: "??? — Conquista secreta",
    icon: "egg-outline",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 150,
    unlockMessage: "Foram muitos ovos. Muitos mesmo.",
    condition: (c) => c.sixEggDays >= 1,
  },
  {
    id: "la-ele",
    title: "Lá ele",
    description: "Registrou banana e whey na mesma refeição.",
    lockedHint: "??? — Conquista secreta",
    icon: "fruit-banana",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 250,
    unlockMessage: "Banana e whey. Lá ele.",
    condition: (c) => c.bananaWheyMeals >= 1,
  },
  {
    id: "cafe-pedreiro",
    title: "Café da manhã de pedreiro",
    description: "Registrou um café da manhã com 700 kcal ou mais.",
    lockedHint: "??? — Conquista secreta",
    icon: "bowl-mix-outline",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 180,
    unlockMessage: "Esse café da manhã sustenta uma obra.",
    condition: (c) => c.bigBreakfasts >= 1,
  },
  {
    id: "urso-madrugada",
    title: "Urso da Madrugada",
    description: "Registrou uma refeição entre meia-noite e 4h59.",
    lockedHint: "??? — Conquista secreta",
    icon: "weather-night",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 175,
    unlockMessage: "A floresta também tem turno da madrugada.",
    condition: (c) => c.midnightMeals >= 1,
  },
  {
    id: "vampiros",
    title: "Vampiros não são problema",
    description: "Registrou alho em 10 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "garlic",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 300,
    unlockMessage: "A caverna está oficialmente protegida.",
    condition: (c) => c.garlicMeals >= 10,
  },
  {
    id: "queijo-proteina",
    title: "Queijo é proteína. Não discuta.",
    description: "Registrou queijo em 30 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "cheese",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 350,
    unlockMessage: "O conselho do queijo encerrou a discussão.",
    condition: (c) => c.cheeseMeals >= 30,
  },
  {
    id: "cafeina",
    title: "Movido a cafeína e decisões questionáveis",
    description: "Registrou café em 50 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "coffee",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 500,
    unlockMessage: "Decisões questionáveis. Cafeína impecável.",
    condition: (c) => c.coffeeMeals >= 50,
  },
];

export function findAchievement(id: string) {
  return ACHIEVEMENTS.find((achievement) => achievement.id === id) ?? null;
}
