import type { AchievementDefinition, AchievementRarity } from "./types";

export const RARITY_COLORS: Record<AchievementRarity, string> = {
  Comum: "#A9A9B2",
  Rara: "#0A84FF",
  Épica: "#BF5AF2",
  Lendária: "#FF9F0A",
  "Urso Mítico": "#B7FF2A",
};

export const ACHIEVEMENTS: AchievementDefinition[] = [
  {
    id: "primeira-patada",
    title: "Primeira Patada",
    description: "Registrou a primeira refeição.",
    lockedHint: "Registre sua primeira refeição.",
    icon: "paw",
    category: "Primeiros passos",
    rarity: "Comum",
    xpReward: 50,
    unlockMessage: "A primeira patada deixa marca.",
    condition: (c) => c.totalMeals >= 1,
  },
  {
    id: "urso-voltou",
    title: "O Urso Voltou",
    description: "Registrou refeições durante 3 dias consecutivos.",
    lockedHint: "Volte e registre refeições por 3 dias seguidos.",
    icon: "teddy-bear",
    category: "Primeiros passos",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Três dias alimentando a máquina.",
    condition: (c) => c.bestStreak >= 3,
  },
  {
    id: "semana-honesta",
    title: "Uma Semaninha Honesta",
    description: "Manteve uma sequência de 7 dias.",
    lockedHint: "Alcance uma sequência de 7 dias.",
    icon: "fire",
    category: "Primeiros passos",
    rarity: "Rara",
    xpReward: 150,
    unlockMessage: "Consistência com cheiro de vitória.",
    condition: (c) => c.bestStreak >= 7,
  },
  {
    id: "pata-firme",
    title: "Firme igual pata de urso",
    description: "Manteve uma sequência de 14 dias.",
    lockedHint: "Alcance uma sequência de 14 dias.",
    icon: "paw-outline",
    category: "Primeiros passos",
    rarity: "Épica",
    xpReward: 250,
    unlockMessage: "Duas semanas. Essa pata está firme.",
    condition: (c) => c.bestStreak >= 14,
  },
  {
    id: "virou-rotina",
    title: "Isso aqui virou rotina",
    description: "Manteve uma sequência de 30 dias.",
    lockedHint: "Alcance uma sequência de 30 dias.",
    icon: "calendar-check",
    category: "Primeiros passos",
    rarity: "Épica",
    xpReward: 400,
    unlockMessage: "A rotina já sabe seu nome.",
    condition: (c) => c.bestStreak >= 30,
  },
  {
    id: "virou-personalidade",
    title: "Isso já virou personalidade",
    description: "Manteve uma sequência de 60 dias.",
    lockedHint: "Alcance uma sequência de 60 dias.",
    icon: "calendar-star",
    category: "Primeiros passos",
    rarity: "Lendária",
    xpReward: 800,
    unlockMessage: "A constância agora faz parte do personagem.",
    condition: (c) => c.bestStreak >= 60,
  },
  {
    id: "absoluto",
    title: "ABSOLUTO",
    description: "Manteve uma sequência de 100 dias.",
    lockedHint: "A floresta conta os dias de uma lenda.",
    icon: "crown",
    category: "Primeiros passos",
    rarity: "Urso Mítico",
    xpReward: 1500,
    unlockMessage: "Cem dias. Absolutamente enorme.",
    condition: (c) => c.bestStreak >= 100,
  },
  {
    id: "proteina-sobrenome",
    title: "Proteína é meu sobrenome",
    description: "Bateu a meta de proteína pela primeira vez.",
    lockedHint: "Alcance a meta diária de proteína.",
    icon: "arm-flex",
    category: "Proteína",
    rarity: "Rara",
    xpReward: 100,
    unlockMessage: "Hoje o urso alimentou os músculos.",
    condition: (c) => c.proteinGoalDays >= 1,
  },
  {
    id: "cade-whey",
    title: "Cadê o Whey?",
    description: "Registrou whey pela primeira vez.",
    lockedHint: "Há rumores de um shaker pela floresta.",
    icon: "shaker-outline",
    category: "Proteína",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Shaker localizado. Missão cumprida.",
    condition: (c) => c.wheyMeals >= 1,
  },
  {
    id: "wheyyyyy",
    title: "WHEYYYYY",
    description: "Registrou whey 50 vezes.",
    lockedHint: "O shaker ainda tem muitas histórias.",
    icon: "shaker",
    category: "Proteína",
    rarity: "Épica",
    xpReward: 500,
    unlockMessage: "A floresta inteira ouviu esse WHEYYYYY.",
    condition: (c) => c.wheyMeals >= 50,
  },
  {
    id: "inimigo-galinhas",
    title: "Inimigo Natural das Galinhas",
    description: "Registrou frango 100 vezes.",
    lockedHint: "Continue registrando suas fontes de proteína.",
    icon: "food-drumstick",
    category: "Proteína",
    rarity: "Épica",
    xpReward: 500,
    unlockMessage: "As galinhas já conhecem a lenda.",
    condition: (c) => c.chickenMeals >= 100,
  },
  {
    id: "urso-onivoro",
    title: "Urso Onívoro",
    description: "Consumiu alimentos de 5 categorias no mesmo dia.",
    lockedHint: "Explore mais cores e categorias no prato.",
    icon: "food-apple-outline",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 200,
    unlockMessage: "A variedade também alimenta o shape.",
    condition: (c) => c.variedFoodDays >= 1,
  },
  {
    id: "equilibrio-padawan",
    title: "Equilíbrio, jovem padawan",
    description: "Terminou o dia dentro de 5% da meta calórica.",
    lockedHint: "Chegue com leveza perto da meta do dia.",
    icon: "scale-balance",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 150,
    unlockMessage: "Equilíbrio desbloqueado. Sem neura.",
    condition: (c) => c.calorieBalanceDays >= 1,
  },
  {
    id: "refeicao-livre",
    title: "Nem só de frango vive o urso",
    description: "Registrou uma refeição livre.",
    lockedHint: "Uma refeição diferente também cabe na rotina.",
    icon: "pizza",
    category: "Alimentação",
    rarity: "Comum",
    xpReward: 100,
    unlockMessage: "Flexibilidade também faz parte do plano.",
    condition: (c) => c.freeMeals >= 1,
  },
  {
    id: "tudo-sob-controle",
    title: "Tudo sob controle",
    description: "Fez uma refeição mais calórica e terminou o dia perto da meta.",
    lockedHint: "Equilíbrio vale mais do que perfeição.",
    icon: "meditation",
    category: "Alimentação",
    rarity: "Épica",
    xpReward: 300,
    unlockMessage: "O urso sabe equilibrar as coisas.",
    condition: (c) => c.controlledHighCalorieDays >= 1,
  },
  {
    id: "plot-twist",
    title: "Plot Twist Nutricional",
    description: "Registrou uma refeição com mais de 1.000 kcal.",
    lockedHint: "Algumas refeições chegam com reviravolta.",
    icon: "hamburger",
    category: "Alimentação",
    rarity: "Rara",
    xpReward: 125,
    unlockMessage: "Plot twist registrado. Vida que segue.",
    condition: (c) => c.veryHighCalorieMeals >= 1,
  },
  {
    id: "acontece",
    title: "Acontece nas melhores famílias",
    description: "Ultrapassou a meta calórica e continuou registrando.",
    lockedHint: "Registrar com honestidade sempre conta.",
    icon: "emoticon-happy-outline",
    category: "Alimentação",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Sem culpa. Informação ajuda, julgamento não.",
    condition: (c) => c.overGoalDays >= 1,
  },
  {
    id: "voltou-normal",
    title: "Voltou como se nada tivesse acontecido",
    description: "Depois de ultrapassar a meta, registrou no dia seguinte.",
    lockedHint: "Retornar à rotina é uma grande conquista.",
    icon: "restart",
    category: "Alimentação",
    rarity: "Épica",
    xpReward: 350,
    unlockMessage: "Consistência não exige perfeição.",
    condition: (c) => c.returnedAfterOverGoal,
  },
  {
    id: "hidraturso",
    title: "HidratUrso",
    description: "Bateu a meta diária de água.",
    lockedHint: "Complete sua meta diária de água.",
    icon: "water",
    category: "Água",
    rarity: "Comum",
    xpReward: 75,
    unlockMessage: "Hidratação premium desbloqueada.",
    condition: (c) => c.waterGoalDays >= 1,
  },
  {
    id: "aquaman-academia",
    title: "Aquaman da Academia",
    description: "Bateu a meta de água por 7 dias consecutivos.",
    lockedHint: "Mantenha a meta de água por uma semana.",
    icon: "waves",
    category: "Água",
    rarity: "Rara",
    xpReward: 250,
    unlockMessage: "Sete dias navegando na hidratação.",
    condition: (c) => c.waterBestStreak >= 7,
  },
  {
    id: "agua-premium",
    title: "100% Água Premium",
    description: "Bateu a meta de água por 30 dias consecutivos.",
    lockedHint: "Transforme hidratação em rotina.",
    icon: "cup-water",
    category: "Água",
    rarity: "Lendária",
    xpReward: 750,
    unlockMessage: "A hidratação agora é lendária.",
    condition: (c) => c.waterBestStreak >= 30,
  },
  {
    id: "muitos-ovos",
    title: "Ovos. Muitos ovos.",
    description: "Registrou 6 ou mais ovos no mesmo dia.",
    lockedHint: "??? — Conquista secreta",
    icon: "egg-outline",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 150,
    unlockMessage: "Foram muitos ovos. Muitos mesmo.",
    condition: (c) => c.sixEggDays >= 1,
  },
  {
    id: "la-ele",
    title: "Lá ele",
    description: "Registrou banana e whey na mesma refeição.",
    lockedHint: "??? — Conquista secreta",
    icon: "fruit-banana",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 250,
    unlockMessage: "Banana e whey. Lá ele.",
    condition: (c) => c.bananaWheyMeals >= 1,
  },
  {
    id: "cafe-pedreiro",
    title: "Café da manhã de pedreiro",
    description: "Registrou um café da manhã com 700 kcal ou mais.",
    lockedHint: "??? — Conquista secreta",
    icon: "bowl-mix-outline",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 180,
    unlockMessage: "Esse café da manhã sustenta uma obra.",
    condition: (c) => c.bigBreakfasts >= 1,
  },
  {
    id: "urso-madrugada",
    title: "Urso da Madrugada",
    description: "Registrou uma refeição entre meia-noite e 4h59.",
    lockedHint: "??? — Conquista secreta",
    icon: "weather-night",
    category: "Secretas",
    rarity: "Rara",
    hidden: true,
    xpReward: 175,
    unlockMessage: "A floresta também tem turno da madrugada.",
    condition: (c) => c.midnightMeals >= 1,
  },
  {
    id: "vampiros",
    title: "Vampiros não são problema",
    description: "Registrou alho em 10 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "garlic",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 300,
    unlockMessage: "A caverna está oficialmente protegida.",
    condition: (c) => c.garlicMeals >= 10,
  },
  {
    id: "queijo-proteina",
    title: "Queijo é proteína. Não discuta.",
    description: "Registrou queijo em 30 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "cheese",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 350,
    unlockMessage: "O conselho do queijo encerrou a discussão.",
    condition: (c) => c.cheeseMeals >= 30,
  },
  {
    id: "cafeina",
    title: "Movido a cafeína e decisões questionáveis",
    description: "Registrou café em 50 refeições.",
    lockedHint: "??? — Conquista secreta",
    icon: "coffee",
    category: "Secretas",
    rarity: "Épica",
    hidden: true,
    xpReward: 500,
    unlockMessage: "Decisões questionáveis. Cafeína impecável.",
    condition: (c) => c.coffeeMeals >= 50,
  },
];

export function findAchievement(id: string) {
  return ACHIEVEMENTS.find((achievement) => achievement.id === id) ?? null;
}
