/**
 * Conteúdo canônico da Jornada UrsoGame.
 * Fonte: UrsoGame_Relatorio_Sem_Imagens.docx, versão consolidada de 04/10/2026.
 * A produção gráfica dos colecionáveis é deliberadamente tratada em separado.
 */
export interface OfficialLevelContent {
  title: string;
  description: string;
}

export const OFFICIAL_LEVEL_CONTENT: readonly OfficialLevelContent[] = [
  { title: "Ursinho Desperto", description: "Toda grande jornada começa quando alguém finalmente abre os olhos." },
  { title: "Saindo da Toca", description: "O primeiro desafio nem sempre é treinar. Às vezes é só sair da toca mesmo." },
  { title: "Primeiros Passos", description: "Um pequeno passo para o urso, um grande passo para a sua rotina." },
  { title: "Urso Persistente", description: "Nem todo dia é grandioso. O importante é aparecer." },
  { title: "Guardião da Rotina", description: "A rotina começou a nascer. Agora ela precisa ser protegida." },
  { title: "Ritmo Encontrado", description: "Motivação vai e volta. Ritmo é o que faz você continuar." },
  { title: "Caminho Aberto", description: "Você não está mais parado. A trilha já reconhece seus passos." },
  { title: "Passos Firmes", description: "Ainda não é velocidade. É constância com convicção." },
  { title: "Quase um Hábito", description: "Você já não depende tanto do 'amanhã eu começo'." },
  { title: "Primeira Insígnia", description: "Parabéns, treinador... digo, aventureiro. A jornada começou de verdade." },
  { title: "Urso Comprometido", description: "Você deixou de testar. Agora está se comprometendo." },
  { title: "Força do Hábito", description: "Pequenas ações repetidas começam a parecer magia." },
  { title: "Pequenas Vitórias", description: "Nem todo troféu faz barulho. Alguns só fazem diferença." },
  { title: "Constância Silenciosa", description: "O progresso gosta de gente que não precisa anunciar tudo." },
  { title: "Raízes Fortes", description: "O que cresce bonito costuma começar por baixo da terra." },
  { title: "Dia Após Dia", description: "Não parece épico... e é exatamente assim que funciona." },
  { title: "Ritual da Toca", description: "Alguns chamam de rotina. Outros de ritual sagrado." },
  { title: "Companheiro da Rotina", description: "A rotina já não é inimiga. Ela sentou do seu lado." },
  { title: "Caminho Conhecido", description: "O início já não assusta. Você sabe por onde ir." },
  { title: "Urso Disciplinado", description: "Motivação é visita. Disciplina já mora aqui." },
  { title: "Além da Toca", description: "Existe um mundo inteiro depois do 'não tô com vontade'." },
  { title: "Trilha Conhecida", description: "Você não está perdido; só está indo mais longe do que antes." },
  { title: "Passos de Aventureiro", description: "Sua rotina ganhou espírito de jornada." },
  { title: "Urso Explorador", description: "Quem sai da toca descobre que o mundo é maior do que o sofá." },
  { title: "Primeiro Marco", description: "Você chegou num ponto em que dá para olhar para trás e sorrir." },
  { title: "Caminho das Pedras", description: "Nem todo terreno é confortável. Ainda bem." },
  { title: "Subindo a Colina", description: "O cenário muda quando você continua mesmo cansado." },
  { title: "Fôlego de Aventureiro", description: "Você aprendeu que respirar fundo também é estratégia." },
  { title: "Horizonte Novo", description: "Quanto mais você anda, mais o mapa cresce." },
  { title: "Guardião da Trilha", description: "Você não apenas segue o caminho. Agora parece fazer parte dele." },
  { title: "Urso Determinado", description: "Determinação é continuar mesmo sem trilha sonora épica." },
  { title: "Força em Construção", description: "Nem toda evolução aparece no espelho primeiro." },
  { title: "Mais Forte que Ontem", description: "A competição mais justa continua sendo contra o seu eu de ontem." },
  { title: "Passo Pesado", description: "Seus passos já fazem o chão perceber sua presença." },
  { title: "Patas Firmes", description: "Base forte, mente estável, rotina viva." },
  { title: "Urso Resistente", description: "A força impressiona. A resistência sustenta." },
  { title: "Força Interior", description: "O verdadeiro upgrade quase nunca é só físico." },
  { title: "Ritmo de Ferro", description: "O corpo cansa. O hábito empurra." },
  { title: "Coragem Renovada", description: "Às vezes a coragem volta depois do banho e da creatina." },
  { title: "Guardião da Força", description: "A força deixou de ser meta. Já é parte da sua identidade." },
  { title: "Viajante Experiente", description: "Não é mais começo de jornada. É bagagem." },
  { title: "A Resposta do Caminho", description: "Você chegou até aqui buscando respostas. Pena que ninguém lembrou a pergunta." },
  { title: "Urso Experiente", description: "Você já sabe reconhecer o que é cansaço... e o que é desculpa." },
  { title: "Caminho sem Atalhos", description: "Infelizmente, o portal mágico ainda não foi desbloqueado." },
  { title: "Persistência Rara", description: "Pouca gente entende o poder de insistir com elegância." },
  { title: "Além do Cansaço", description: "Às vezes a linha entre desistir e evoluir dura mais cinco minutos." },
  { title: "Passos de Veterano", description: "Seus passos carregam memória. E um pouco de dor na panturrilha também." },
  { title: "Força e Equilíbrio", description: "Ficar forte é bom. Permanecer inteiro é melhor." },
  { title: "Quase Mestre", description: "Você ainda não virou lenda. Mas já está dando trabalho pros iniciantes." },
  { title: "Metade da Montanha", description: "Metade do caminho. O bom é que a vista já começou a compensar." },
  { title: "Urso Montanhista", description: "O terreno ficou mais inclinado, mas você também ficou maior." },
  { title: "Terreno Elevado", description: "Você começou a habitar lugares que antes pareciam difíceis demais." },
  { title: "Subida Constante", description: "Nem rápido, nem bonito. Só constante. E isso resolve muita coisa." },
  { title: "Sem Voltar Atrás", description: "Não porque não dá, mas porque já não faz sentido." },
  { title: "Acima das Nuvens", description: "Você descobriu que alguns cenários só aparecem pra quem continua subindo." },
  { title: "Passos nas Alturas", description: "O medo ainda existe. Só não manda mais." },
  { title: "Resistência Ancestral", description: "Há uma energia antiga em quem aprende a persistir." },
  { title: "Urso Implacável", description: "Não confundir com raiva. É só consistência em estado bruto." },
  { title: "O Caminho Continua", description: "O topo sempre revela outro topo. Curiosamente, isso é animador." },
  { title: "Guardião da Montanha", description: "Você já não parece visitante. Parece parte da paisagem." },
  { title: "Urso Incansável", description: "Cansa, sim. Só não para." },
  { title: "Chama Interior", description: "Alguns combustíveis não vêm em pote." },
  { title: "Dias Difíceis", description: "Nem todo vilão tem rosto. Às vezes ele atende por preguiça." },
  { title: "Ainda de Pé", description: "Se você permaneceu, já venceu mais do que parece." },
  { title: "Força Renovada", description: "Às vezes o upgrade vem depois da pausa certa." },
  { title: "Depois da Tempestade", description: "Há algo de mágico na calmaria depois de um período difícil." },
  { title: "Mais Uma Vez", description: "Heróis e hábitos têm isso em comum: voltam no dia seguinte." },
  { title: "Além dos Limites", description: "Muitos limites eram só cercas mal posicionadas." },
  { title: "Equilíbrio Perfeito", description: "Algumas conquistas são autoexplicativas. Esta, por educação, deixaremos em silêncio." },
  { title: "Guardião da Chama", description: "A chama não é mais acaso. Você aprendeu a cuidar dela." },
  { title: "Urso Mestre", description: "Não porque sabe tudo. Mas porque aprendeu a continuar." },
  { title: "Mestre da Rotina", description: "A rotina já não exige negociação diária." },
  { title: "Passos Precisos", description: "Menos desperdício. Mais intenção." },
  { title: "Força Tranquila", description: "A verdadeira força raramente precisa fazer alarde." },
  { title: "Veterano da Toca", description: "Você se lembra de onde começou — e isso torna tudo melhor." },
  { title: "Caminho Dominado", description: "O mapa deixou de ser um mistério. Agora é território conhecido." },
  { title: "Disciplina Natural", description: "O que antes era esforço, agora parece parte da sua natureza." },
  { title: "Mestre dos Hábitos", description: "Pequenas repetições: o superpoder mais subestimado do mundo." },
  { title: "Urso Inabalável", description: "O vento muda. A rotina não." },
  { title: "Guardião do Equilíbrio", description: "Força, descanso, constância e leveza finalmente aprenderam a morar juntos." },
  { title: "Urso Excepcional", description: "Você começou a se destacar até do seu eu imaginário." },
  { title: "Além da Rotina", description: "Isso já não é só hábito. É identidade." },
  { title: "Marca do Veterano", description: "Todo aventureiro de verdade carrega sinais da jornada." },
  { title: "Trilha Lendária", description: "Há caminhos que se tornam lenda porque alguém insistiu neles." },
  { title: "Guardião Antigo", description: "Sua rotina parece ter sido escrita em pedra." },
  { title: "Urso de Muitas Jornadas", description: "Você já não acumula dias. Acumula capítulos." },
  { title: "Sabedoria da Toca", description: "Nem todo conhecimento vem de livros. Às vezes vem de repetir o básico muito bem." },
  { title: "Caminhante das Estrelas", description: "Seus passos parecem guiados por alguma força... cósmica, talvez." },
  { title: "Força Desperta", description: "Sentiu isso? Pode ser evolução. Pode ser o pré-treino." },
  { title: "Guardião da Jornada", description: "Você não só venceu etapas. Você se tornou símbolo do caminho." },
  { title: "Urso Ascendente", description: "Já não dá para falar em progresso. Agora é ascensão mesmo." },
  { title: "Além da Montanha", description: "O topo era só o começo do que vinha depois." },
  { title: "Guardião Supremo", description: "Você protege aquilo que construiu porque sabe o valor de cada passo." },
  { title: "Urso Lendário", description: "Alguns ouvem falar. Poucos chegam aqui." },
  { title: "Brilho Raro", description: "Há quem passe a vida inteira sem encontrar um destes." },
  { title: "Lenda da Floresta", description: "Seu nome já circula pela mata em tom de respeito... e leve inveja." },
  { title: "Mestre da Jornada", description: "Você não venceu apenas níveis. Você aprendeu a jornada." },
  { title: "Último Desafio", description: "Todo final digno precisa de um último portal." },
  { title: "Guardião da Toca", description: "Você voltou ao início, mas já não é o mesmo urso que saiu de lá." },
  { title: "Lenda UrsoFit", description: "O urso despertou, caminhou, caiu, subiu, brilhou — e virou lenda." },
] as const;
