import MaterialDesignIcons from "@react-native-vector-icons/material-design-icons";
import { useFocusEffect, useRouter } from "expo-router";
import { useCallback, useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { evaluateGamification } from "../src/gamification/engine";
import { AVATAR_DEFINITIONS, TITLE_DEFINITIONS, type CosmeticDefinition } from "../src/gamification/cosmetics";
import { equipCosmetic, getProfileState, saveProfileState, unlockEligibleCosmetics } from "../src/profile/store";
import type { ProfileState } from "../src/profile/types";
import { colors, radius, spacing, withAlpha } from "../src/theme";

export default function BearClosetScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { width } = useWindowDimensions();
  const [state, setState] = useState<ProfileState | null>(null); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState<string | null>(null);
  const columns = width >= 1000 ? 4 : width >= 620 ? 3 : 2;
  const load = useCallback(async () => { setLoading(true); try { const [profile, game] = await Promise.all([getProfileState(), evaluateGamification()]); const next = unlockEligibleCosmetics(profile, game); if (Object.keys(next.unlockedCosmetics).length !== Object.keys(profile.unlockedCosmetics).length) await saveProfileState(next); setState(next); } catch (error) { setNotice(error instanceof Error ? error.message : "Não foi possível abrir o armário."); } finally { setLoading(false); } }, []);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const avatars = useMemo(() => AVATAR_DEFINITIONS.filter((item) => !item.secret || state?.unlockedCosmetics[item.id]), [state]);
  const equip = async (item: CosmeticDefinition) => { if (!state) return; try { const next = equipCosmetic(state, item.kind, item.id); setState(await saveProfileState(next)); setNotice(`${item.name} equipado.`); } catch (error) { setNotice(error instanceof Error ? error.message : "Item bloqueado."); } };
  if (loading || !state) return <View style={styles.center}><ActivityIndicator color={colors.brandPrimary} /><Text style={styles.muted}>Abrindo o armário do urso…</Text></View>;
  return <ScrollView style={styles.screen} contentContainerStyle={[styles.content, { paddingTop: insets.top + spacing.lg, paddingBottom: insets.bottom + spacing.xxxl }]} testID="bear-closet-screen"><View style={styles.header}><Pressable style={styles.back} onPress={() => router.back()} accessibilityLabel="Voltar"><MaterialDesignIcons name="chevron-left" size={25} color={colors.onSurface} /></Pressable><View><Text style={styles.eyebrow}>COLEÇÃO PESSOAL</Text><Text style={styles.title}>Meu Urso</Text></View></View>{notice ? <View style={styles.notice}><Text style={styles.noticeText}>{notice}</Text></View> : null}<Text style={styles.sectionTitle}>Avatares da Toca</Text><View style={styles.grid}>{avatars.map((item) => { const unlocked = Boolean(state.unlockedCosmetics[item.id]); const equipped = state.equipped.avatar === item.id; return <Pressable key={item.id} style={[styles.card, { width: `${100 / columns - 2}%` }, equipped && styles.equipped]} onPress={() => void equip(item)} accessibilityRole="button" accessibilityState={{ disabled: !unlocked, selected: equipped }} accessibilityLabel={`${item.name}, ${unlocked ? equipped ? "equipado" : "desbloqueado" : "bloqueado"}`}><View style={[styles.art, !unlocked && styles.locked]}>{item.id === "avatar-01" ? <Image source={require("../assets/images/mascot-whey.jpg")} style={styles.image} /> : <MaterialDesignIcons name={unlocked ? "teddy-bear" : "lock-outline"} size={44} color={unlocked ? colors.brandPrimary : colors.onSurfaceTertiary} />}</View><Text style={styles.cardTitle} numberOfLines={2}>{item.name}</Text><Text style={styles.cardMeta}>{unlocked ? equipped ? "Equipado" : "Toque para equipar" : item.secret ? "Secreto" : "Bloqueado"}</Text></Pressable>; })}</View><Text style={styles.sectionTitle}>Títulos</Text><View style={styles.titleList}>{TITLE_DEFINITIONS.map((item) => { const unlocked = Boolean(state.unlockedCosmetics[item.id]); const equipped = state.equipped.title === item.id; return <Pressable key={item.id} style={[styles.titleRow, equipped && styles.equipped]} onPress={() => void equip(item)} accessibilityState={{ disabled: !unlocked, selected: equipped }}><MaterialDesignIcons name={unlocked ? "star-four-points" : "lock-outline"} size={18} color={unlocked ? "#F6C85F" : colors.onSurfaceTertiary} /><View style={{ flex: 1 }}><Text style={styles.titleName}>{item.name}</Text><Text style={styles.muted}>{unlocked ? equipped ? "Título equipado" : "Disponível" : "Continue sua jornada para desbloquear"}</Text></View></Pressable>; })}</View></ScrollView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: colors.surface }, content: { width: "100%", maxWidth: 1080, alignSelf: "center", paddingHorizontal: spacing.lg, gap: spacing.lg }, center: { flex: 1, alignItems: "center", justifyContent: "center", gap: spacing.md, backgroundColor: colors.surface }, header: { flexDirection: "row", alignItems: "center", gap: spacing.md }, back: { width: 44, height: 44, borderRadius: radius.md, alignItems: "center", justifyContent: "center", backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border }, eyebrow: { color: colors.brandPrimary, fontSize: 10, fontWeight: "900", letterSpacing: 1.4 }, title: { color: colors.onSurface, fontSize: 24, fontWeight: "900" }, sectionTitle: { color: colors.onSurface, fontSize: 17, fontWeight: "900" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, card: { minWidth: 140, flexGrow: 1, gap: spacing.sm, padding: spacing.md, borderRadius: radius.lg, backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border }, equipped: { borderColor: colors.brandPrimary, backgroundColor: withAlpha(colors.brandPrimary, 0.1) }, art: { height: 116, alignItems: "center", justifyContent: "center", overflow: "hidden", borderRadius: radius.md, backgroundColor: colors.surfaceTertiary }, locked: { opacity: 0.58 }, image: { width: "100%", height: "100%" }, cardTitle: { color: colors.onSurface, fontSize: 12, fontWeight: "900" }, cardMeta: { color: colors.onSurfaceTertiary, fontSize: 9 }, titleList: { gap: spacing.sm }, titleRow: { minHeight: 58, flexDirection: "row", alignItems: "center", gap: spacing.md, padding: spacing.md, borderRadius: radius.md, backgroundColor: colors.surfaceSecondary, borderWidth: 1, borderColor: colors.border }, titleName: { color: colors.onSurface, fontSize: 11, fontWeight: "800" }, muted: { color: colors.onSurfaceTertiary, fontSize: 9, lineHeight: 14 }, notice: { padding: spacing.md, borderRadius: radius.md, backgroundColor: withAlpha(colors.brandTertiary, 0.12), borderWidth: 1, borderColor: withAlpha(colors.brandTertiary, 0.35) }, noticeText: { color: colors.onSurfaceSecondary, fontSize: 11 } });
